import { FixtureItem } from './types';

export const DEFAULT_FIXTURE_LIBRARY: FixtureItem[] = [
  // ==========================================
  // --- 1. LED PANELS (2x2, 1x4, SURFACE & RECESSED) ---
  // ==========================================
  {
    id: 'fix-panel-36w-ssg',
    manufacturer: 'Super Star Group (SSG)',
    model: '600x600 Ultra-Slim LED Panel 36W (Daylight)',
    type: 'LED Panel',
    powerWatts: 36,
    lumens: 3600,
    beamAngle: 120,
    cct: 6500,
    cri: 82,
    ugr: 18.5,
    ipRating: 'IP20',
    lampsPerFixture: 1
  },
  {
    id: 'fix-panel-36w-ssg-warm',
    manufacturer: 'Super Star Group (SSG)',
    model: '600x600 Ultra-Slim LED Panel 36W (Warm White)',
    type: 'LED Panel',
    powerWatts: 36,
    lumens: 3420,
    beamAngle: 120,
    cct: 3000,
    cri: 82,
    ugr: 18.5,
    ipRating: 'IP20',
    lampsPerFixture: 1
  },
  {
    id: 'fix-panel-40w-philips',
    manufacturer: 'Philips Lighting',
    model: 'SmartBright LED Panel RC091V 40W 2x2',
    type: 'LED Panel',
    powerWatts: 40,
    lumens: 4000,
    beamAngle: 120,
    cct: 6500,
    cri: 85,
    ugr: 17.8,
    ipRating: 'IP20',
    lampsPerFixture: 1
  },
  {
    id: 'fix-panel-40w-philips-neutral',
    manufacturer: 'Philips Lighting',
    model: 'SmartBright LED Panel RC091V 40W 4000K',
    type: 'LED Panel',
    powerWatts: 40,
    lumens: 4000,
    beamAngle: 120,
    cct: 4000,
    cri: 85,
    ugr: 17.8,
    ipRating: 'IP20',
    lampsPerFixture: 1
  },
  {
    id: 'fix-panel-48w-transtec',
    manufacturer: 'Transtec Electrical',
    model: 'ProLine Recessed LED Panel 48W 2x2',
    type: 'LED Panel',
    powerWatts: 48,
    lumens: 4800,
    beamAngle: 120,
    cct: 6500,
    cri: 80,
    ugr: 19.0,
    ipRating: 'IP20',
    lampsPerFixture: 1
  },
  {
    id: 'fix-panel-24w-walton',
    manufacturer: 'Walton Micro-Tech',
    model: 'Square LED Surface Panel 24W',
    type: 'LED Panel',
    powerWatts: 24,
    lumens: 2280,
    beamAngle: 110,
    cct: 6500,
    cri: 80,
    ugr: 19.5,
    ipRating: 'IP20',
    lampsPerFixture: 1
  },
  {
    id: 'fix-panel-60w-energypac',
    manufacturer: 'Energypac Electronics',
    model: 'Heavy Commercial LED Panel 60W (300x1200mm)',
    type: 'LED Panel',
    powerWatts: 60,
    lumens: 6300,
    beamAngle: 120,
    cct: 6500,
    cri: 82,
    ugr: 18.0,
    ipRating: 'IP20',
    lampsPerFixture: 1
  },
  {
    id: 'fix-panel-40w-opple',
    manufacturer: 'Opple Lighting',
    model: 'LED Panel Pro II 40W High Efficiency',
    type: 'LED Panel',
    powerWatts: 40,
    lumens: 4400,
    beamAngle: 120,
    cct: 6500,
    cri: 85,
    ugr: 17.0,
    ipRating: 'IP20',
    lampsPerFixture: 1
  },

  // ==========================================
  // --- 2. DOWNLIGHTS & RECESSED SPOTLIGHTS ---
  // ==========================================
  {
    id: 'fix-downlight-6w-walton',
    manufacturer: 'Walton Micro-Tech',
    model: 'Micro Recessed Downlight 6W',
    type: 'Downlight',
    powerWatts: 6,
    lumens: 510,
    beamAngle: 90,
    cct: 6500,
    cri: 80,
    ugr: 20.0,
    ipRating: 'IP20',
    lampsPerFixture: 1
  },
  {
    id: 'fix-downlight-9w-ssg',
    manufacturer: 'Super Star Group',
    model: 'Ultra Bright Circular Downlight 9W',
    type: 'Downlight',
    powerWatts: 9,
    lumens: 810,
    beamAngle: 100,
    cct: 6500,
    cri: 80,
    ugr: 20.5,
    ipRating: 'IP20',
    lampsPerFixture: 1
  },
  {
    id: 'fix-downlight-12w-walton',
    manufacturer: 'Walton Micro-Tech',
    model: 'Slim Recessed Downlight 12W',
    type: 'Downlight',
    powerWatts: 12,
    lumens: 1080,
    beamAngle: 90,
    cct: 6500,
    cri: 80,
    ugr: 21.0,
    ipRating: 'IP20',
    lampsPerFixture: 1
  },
  {
    id: 'fix-downlight-15w-philips',
    manufacturer: 'Philips Lighting',
    model: 'Meson Recessed LED Downlight 15W',
    type: 'Downlight',
    powerWatts: 15,
    lumens: 1350,
    beamAngle: 110,
    cct: 6500,
    cri: 80,
    ugr: 19.5,
    ipRating: 'IP20',
    lampsPerFixture: 1
  },
  {
    id: 'fix-downlight-18w-ssg-cob',
    manufacturer: 'Super Star Group',
    model: 'Architectural COB Downlight 18W (Neutral 4000K)',
    type: 'Downlight',
    powerWatts: 18,
    lumens: 1800,
    beamAngle: 60,
    cct: 4000,
    cri: 90,
    ugr: 16.5,
    ipRating: 'IP44',
    lampsPerFixture: 1
  },
  {
    id: 'fix-downlight-24w-osram',
    manufacturer: 'Osram / LEDVANCE',
    model: 'DL Comfort 24W Anti-Glare Downlight',
    type: 'Downlight',
    powerWatts: 24,
    lumens: 2400,
    beamAngle: 100,
    cct: 6500,
    cri: 85,
    ugr: 18.0,
    ipRating: 'IP44',
    lampsPerFixture: 1
  },
  {
    id: 'fix-downlight-30w-schneider',
    manufacturer: 'Schneider Electric',
    model: 'Mureva COB Commercial Downlight 30W',
    type: 'Downlight',
    powerWatts: 30,
    lumens: 3100,
    beamAngle: 60,
    cct: 4000,
    cri: 90,
    ugr: 16.0,
    ipRating: 'IP54',
    lampsPerFixture: 1
  },

  // ==========================================
  // --- 3. LED TUBES & BATTENS (T8, T5, TWIN) ---
  // ==========================================
  {
    id: 'fix-tube-9w-2ft-energypac',
    manufacturer: 'Energypac Electronics',
    model: 'T8 Integrated LED Tube 9W (2 Feet)',
    type: 'Tube',
    powerWatts: 9,
    lumens: 950,
    beamAngle: 140,
    cct: 6500,
    cri: 80,
    ugr: 19.0,
    ipRating: 'IP20',
    lampsPerFixture: 1
  },
  {
    id: 'fix-tube-18w-t8-energypac',
    manufacturer: 'Energypac Electronics',
    model: 'T8 Integrated LED Tube Batten 18W (4 Feet)',
    type: 'Tube',
    powerWatts: 18,
    lumens: 1900,
    beamAngle: 140,
    cct: 6500,
    cri: 80,
    ugr: 20.0,
    ipRating: 'IP20',
    lampsPerFixture: 1
  },
  {
    id: 'fix-tube-20w-ssg-t8',
    manufacturer: 'Super Star Group',
    model: 'Super Bright T8 Glass LED Tube 20W (4 Feet)',
    type: 'Tube',
    powerWatts: 20,
    lumens: 2200,
    beamAngle: 160,
    cct: 6500,
    cri: 82,
    ugr: 20.0,
    ipRating: 'IP20',
    lampsPerFixture: 1
  },
  {
    id: 'fix-tube-22w-philips-ecofit',
    manufacturer: 'Philips Lighting',
    model: 'Ecofit LEDtube 1200mm 22W T8',
    type: 'Tube',
    powerWatts: 22,
    lumens: 2300,
    beamAngle: 160,
    cct: 6500,
    cri: 80,
    ugr: 19.5,
    ipRating: 'IP20',
    lampsPerFixture: 1
  },
  {
    id: 'fix-tube-twin-36w-ssg',
    manufacturer: 'Super Star Group',
    model: 'Double T8 Waterproof Batten 2x18W (36W Total)',
    type: 'Tube',
    powerWatts: 36,
    lumens: 3800,
    beamAngle: 140,
    cct: 6500,
    cri: 80,
    ugr: 21.0,
    ipRating: 'IP65',
    lampsPerFixture: 2
  },
  {
    id: 'fix-tube-twin-40w-transtec',
    manufacturer: 'Transtec Electrical',
    model: 'Heavy Duty Twin Tube Fixture 2x20W (40W Total)',
    type: 'Tube',
    powerWatts: 40,
    lumens: 4400,
    beamAngle: 140,
    cct: 6500,
    cri: 80,
    ugr: 21.0,
    ipRating: 'IP65',
    lampsPerFixture: 2
  },
  {
    id: 'fix-tube-t5-28w-havells',
    manufacturer: 'Havells',
    model: 'Slim T5 Linear Batten 28W (4 Feet)',
    type: 'Tube',
    powerWatts: 28,
    lumens: 2900,
    beamAngle: 130,
    cct: 6500,
    cri: 80,
    ugr: 19.0,
    ipRating: 'IP20',
    lampsPerFixture: 1
  },

  // ==========================================
  // --- 4. HIGH BAYS (FACTORY & WAREHOUSE) ---
  // ==========================================
  {
    id: 'fix-highbay-80w-walton',
    manufacturer: 'Walton Micro-Tech',
    model: 'Industrial UFO High Bay 80W',
    type: 'High Bay',
    powerWatts: 80,
    lumens: 9600,
    beamAngle: 120,
    cct: 6500,
    cri: 80,
    ugr: 22.0,
    ipRating: 'IP65',
    lampsPerFixture: 1
  },
  {
    id: 'fix-highbay-100w-philips',
    manufacturer: 'Philips Lighting',
    model: 'BY698P GreenPerform LED HighBay 100W',
    type: 'High Bay',
    powerWatts: 100,
    lumens: 13000,
    beamAngle: 90,
    cct: 6500,
    cri: 80,
    ugr: 22.0,
    ipRating: 'IP65',
    lampsPerFixture: 1
  },
  {
    id: 'fix-highbay-150w-ssg',
    manufacturer: 'Super Star Group',
    model: 'Industrial UFO LED High Bay 150W',
    type: 'High Bay',
    powerWatts: 150,
    lumens: 19500,
    beamAngle: 120,
    cct: 6500,
    cri: 80,
    ugr: 24.0,
    ipRating: 'IP65',
    lampsPerFixture: 1
  },
  {
    id: 'fix-highbay-200w-osram',
    manufacturer: 'Osram / LEDVANCE',
    model: 'High Bay Value 200W IP65',
    type: 'High Bay',
    powerWatts: 200,
    lumens: 26000,
    beamAngle: 100,
    cct: 6500,
    cri: 80,
    ugr: 25.0,
    ipRating: 'IP65',
    lampsPerFixture: 1
  },

  // ==========================================
  // --- 5. FLOOD LIGHTS (OUTDOOR & FIELD) ---
  // ==========================================
  {
    id: 'fix-flood-30w-ssg',
    manufacturer: 'Super Star Group',
    model: 'Outdoor Slim LED Flood Light 30W',
    type: 'Flood Light',
    powerWatts: 30,
    lumens: 3150,
    beamAngle: 110,
    cct: 6500,
    cri: 80,
    ugr: 24.0,
    ipRating: 'IP66',
    lampsPerFixture: 1
  },
  {
    id: 'fix-flood-50w-transtec',
    manufacturer: 'Transtec Electrical',
    model: 'Outdoor IP66 LED Flood Light 50W',
    type: 'Flood Light',
    powerWatts: 50,
    lumens: 5500,
    beamAngle: 110,
    cct: 6500,
    cri: 80,
    ugr: 25.0,
    ipRating: 'IP66',
    lampsPerFixture: 1
  },
  {
    id: 'fix-flood-100w-osram',
    manufacturer: 'Osram / LEDVANCE',
    model: 'Floodlight Performance 100W',
    type: 'Flood Light',
    powerWatts: 100,
    lumens: 11500,
    beamAngle: 100,
    cct: 6500,
    cri: 80,
    ugr: 26.0,
    ipRating: 'IP66',
    lampsPerFixture: 1
  },
  {
    id: 'fix-flood-150w-philips',
    manufacturer: 'Philips Lighting',
    model: 'BVP150 LED Essential Smartbright Floodlight 150W',
    type: 'Flood Light',
    powerWatts: 150,
    lumens: 17250,
    beamAngle: 110,
    cct: 6500,
    cri: 80,
    ugr: 27.0,
    ipRating: 'IP65',
    lampsPerFixture: 1
  },
  {
    id: 'fix-flood-200w-ssg',
    manufacturer: 'Super Star Group',
    model: 'Heavy Duty Outdoor Flood Light 200W',
    type: 'Flood Light',
    powerWatts: 200,
    lumens: 23000,
    beamAngle: 110,
    cct: 6500,
    cri: 80,
    ugr: 28.0,
    ipRating: 'IP66',
    lampsPerFixture: 1
  },

  // ==========================================
  // --- 6. TRACK LIGHTS & ARCHITECTURAL LINEAR ---
  // ==========================================
  {
    id: 'fix-track-20w-cob',
    manufacturer: 'Super Star Group',
    model: 'COB Ceiling Track Light 20W (3000K Warm)',
    type: 'Spotlight',
    powerWatts: 20,
    lumens: 1900,
    beamAngle: 36,
    cct: 3000,
    cri: 92,
    ugr: 15.0,
    ipRating: 'IP20',
    lampsPerFixture: 1
  },
  {
    id: 'fix-track-30w-opple',
    manufacturer: 'Opple Lighting',
    model: 'Professional COB Track Spotlight 30W',
    type: 'Spotlight',
    powerWatts: 30,
    lumens: 3000,
    beamAngle: 24,
    cct: 4000,
    cri: 90,
    ugr: 14.5,
    ipRating: 'IP20',
    lampsPerFixture: 1
  },
  {
    id: 'fix-linear-40w-suspended',
    manufacturer: 'Philips Lighting',
    model: 'Architectural Suspended Linear Profile 40W 1.2m',
    type: 'LED Panel',
    powerWatts: 40,
    lumens: 4200,
    beamAngle: 110,
    cct: 4000,
    cri: 88,
    ugr: 16.0,
    ipRating: 'IP20',
    lampsPerFixture: 1
  }
];

